site_name: Zypher UI Library Documentation

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'white'
    accent: 'gray'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/styles.css

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

plugins:
  - search

nav:
  - Basics: index.md
  - Interactables: interactables.md